In [1]:
from DeepHedging.HedgingInstruments import GBMStock
from DeepHedging.ContingentClaims import EuropeanCall, EuropeanPut

In [2]:
# Parameters
S0 = 100.0       # Initial stock price
T = 1.0          # Time horizon (1 year)
N = 252          # Number of time steps (daily steps for 1 year)
r = 0.05         # Risk-free rate
sigma = 0.2      # Volatility
strike = 100.0   # Strike price

# Instantiate the GBMStock object
gbm_stock = GBMStock(S0=S0, T=T, N=N, r=r, sigma=sigma)

# Generate paths (e.g., 10,000 paths)
num_paths = 10000
paths = gbm_stock.generate_paths(num_paths=num_paths)


In [5]:
# Instantiate European Call and Put options
european_call = EuropeanCall(strike=strike, amount = 1.0)
european_put = EuropeanPut(strike=strike, amount = 1.0)

# Calculate the payoffs for each option
call_payoff = european_call.calculate_payoff(paths)
put_payoff = european_put.calculate_payoff(paths)

# Display the results
print("Call Payoff Shape:", call_payoff.shape)
print("Put Payoff Shape:", put_payoff.shape)

Call Payoff Shape: (10000,)
Put Payoff Shape: (10000,)


In [6]:
call_payoff

<tf.Tensor: shape=(10000,), dtype=float32, numpy=
array([44.551224,  0.      ,  0.      , ..., 70.94278 , 12.990135,
       28.537003], dtype=float32)>

In [8]:
european_call_short = EuropeanCall(strike=strike, amount= -1.0)
european_put_short = EuropeanPut(strike=strike, amount= -1.0)

call_payoff_short = european_call_short.calculate_payoff(paths)
put_payoff_short = european_put_short.calculate_payoff(paths)

print("Call Payoff with Amount -1.0 Shape:", call_payoff_short.shape)
print("Put Payoff with Amount -1.0 Shape:", put_payoff_short.shape)


Call Payoff with Amount -1.0 Shape: (10000,)
Put Payoff with Amount -1.0 Shape: (10000,)


In [10]:
put_payoff_short

<tf.Tensor: shape=(10000,), dtype=float32, numpy=
array([ -0.      , -11.803688, -21.43135 , ...,  -0.      ,  -0.      ,
        -0.      ], dtype=float32)>