In [3]:
from DeepHedging.HedgingInstruments import GBMStock
from DeepHedging.CostFunctions import ProportionalCost
import tensorflow as tf


In [4]:
# Parameters
S0 = 100.0       # Initial stock price
T = 1.0          # Time horizon (1 year)
N = 252          # Number of time steps (daily steps for 1 year)
r = 0.05         # Risk-free rate
sigma = 0.2      # Volatility
proportion = 0.01  # Proportional cost rate (1%)

# Instantiate the GBMStock object
gbm_stock = GBMStock(S0=S0, T=T, N=N, r=r, sigma=sigma)

# Generate paths (e.g., 10,000 paths)
num_paths = 10000
paths = gbm_stock.generate_paths(num_paths=num_paths)

# Create a random actions tensor (for example purposes)
actions = tf.random.uniform(shape=(num_paths, N), minval=-1, maxval=1)

# Instantiate the ProportionalCost object
proportional_cost = ProportionalCost(proportion=proportion)

# Calculate the proportional transaction costs
transaction_costs = proportional_cost.calculate(actions, paths)

# Display the results
print("Transaction Costs Shape:", transaction_costs.shape)
print("Sample Transaction Costs:", transaction_costs.numpy()[:5])


Transaction Costs Shape: (10000, 252)
Sample Transaction Costs: [[0.6941588  0.7739097  0.13742912 ... 1.002849   0.13391729 1.0037621 ]
 [0.9337329  0.10534301 0.8736474  ... 0.59667027 0.67154986 0.37157637]
 [0.414088   0.31448242 0.7700505  ... 0.7065162  0.41264638 0.88853556]
 [0.33943987 0.8714967  0.54467636 ... 1.1096473  0.46892303 0.75206304]
 [0.81983376 0.24713124 0.26412922 ... 1.094026   1.2205642  0.12964423]]
